name: Parallel Tests & Reports

on:
  push: {}
  workflow_dispatch: {}

jobs:
  tests:
    name: Parallel Tests & Reports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Restore Maven dependencies cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Install (skip tests)
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run tests and generate report
        run: mvn test -Dplaywright.browserName=${{ matrix.browser }} surefire-report:report

      - name: Publish Test Report
        uses: phoenix-actions/test-reporting@v15
        with:
          name: 'Publish test report (surefire)'
          path: target/surefire-reports/TEST*.xml
          reporter: java-junit
          list-tests: all
          list-suites: all
          fail-on-error: true
          output-to: 'step-summary'
